# 模型参数
model:
  in_channels: 2
  out_channels: 2
  in_frames: 4
  out_frames: 4
  bilinear: true
  num_kernel: 2
  reduction_ratio: 16

# 训练参数
train:
  epochs: 200
  lr: 0.001
  optimizer: Adam
  scheduler: ReduceLROnPlateau
  patience: 15
  resume_from:

# 测试参数
test:
  model_path: 
  save_interval: 10