# 数据集配置
MovingMNIST:
  data_path: "Data/MovingMNIST/train-images-idx3-ubyte.gz"
  test_path: "Data/MovingMNIST/mnist_test_seq.npy"
  input_frames: 10
  output_frames: 10
  image_size: 64
  num_digits: [2]
  batch_size_train: 16
  batch_size_val: 4
  num_workers: 4

TaxiBJ:
  data_path: "Data/TaxiBJ/taxibj.npz"
  batch_size_train: 16
  batch_size_val: 4
  num_workers: 4

