# 模型配置
model:
  input_shape: [10, 1, 128, 128]
  hid_channels_S: 64
  hid_channels_T: 512
  layers_S: 4
  layers_T: 3
  inception_kernels: [3, 5, 7, 11]
  groups: 8

# 数据集配置
dataset: Moving_MNIST

# 训练配置
train:
  epochs: 200
  lr: 0.01
  optimizer: Adam
  scheduler: OneCycleLR
  resume_from:

# 测试配置
test:
  model_path: 
  save_interval: 10