# 模型配置
model:
  in_channels: 10
  out_channels: 1
  out_frames: 10
  bilinear: true
  num_kernel: 2
  reduction_ratio: 16

# 数据集配置
dataset: Moving_MNIST

# 训练配置
train:
  epochs: 200
  lr: 0.001
  optimizer: Adam
  scheduler: ReduceLROnPlateau
  resume_from:

# 测试配置
test:
  model_path: 
  save_interval: 10