# 模型配置
model:
  in_channels: 10
  out_channels: 1
  out_frames: 10
  bilinear: true

# 数据集配置
dataset: Moving_MNIST

# 训练配置
train:
  epochs: 200
  lr: 0.001
  optimizer: Adam
  scheduler: ReduceLROnPlateau