# 模型参数
model:
  in_channels: 1
  out_channels: 1
  in_frames: 10
  out_frames: 10
  bilinear: true
  num_kernel: 2
  reduction_ratio: 16

# 训练参数
epochs: 200
lr: 0.001
optimizer: Adam
scheduler: ReduceLROnPlateau
patience: 20
seed: 42
resume_from: 

# 测试参数
model_path: 
save_interval: 10